package com.ft.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-10-23T15:16:09.518+07:00
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "tns:ns", name = "SOAP_MCA")
@XmlSeeAlso({ObjectFactory.class})
public interface SOAPMCA {

    @WebMethod
    @RequestWrapper(localName = "sendLU", targetNamespace = "tns:ns", className = "com.ft.soap.SendLU")
    @ResponseWrapper(localName = "sendLUResponse", targetNamespace = "tns:ns", className = "com.ft.soap.SendLUResponse")
    @WebResult(name = "response", targetNamespace = "tns:ns")
    public com.ft.soap.Result sendLU(
        @WebParam(name = "tid", targetNamespace = "tns:ns")
        java.lang.String tid,
        @WebParam(name = "imsi", targetNamespace = "tns:ns")
        java.lang.String imsi,
        @WebParam(name = "cdpa", targetNamespace = "tns:ns")
        java.lang.String cdpa,
        @WebParam(name = "cgpa", targetNamespace = "tns:ns")
        java.lang.String cgpa
    );

    @WebMethod
    @RequestWrapper(localName = "sendCL", targetNamespace = "tns:ns", className = "com.ft.soap.SendCL")
    @ResponseWrapper(localName = "sendCLResponse", targetNamespace = "tns:ns", className = "com.ft.soap.SendCLResponse")
    @WebResult(name = "response", targetNamespace = "tns:ns")
    public com.ft.soap.Result sendCL(
        @WebParam(name = "tid", targetNamespace = "tns:ns")
        java.lang.String tid,
        @WebParam(name = "imsi", targetNamespace = "tns:ns")
        java.lang.String imsi,
        @WebParam(name = "cdpa", targetNamespace = "tns:ns")
        java.lang.String cdpa,
        @WebParam(name = "cgpa", targetNamespace = "tns:ns")
        java.lang.String cgpa
    );

    @WebMethod
    @RequestWrapper(localName = "sendISD", targetNamespace = "tns:ns", className = "com.ft.soap.SendISD")
    @ResponseWrapper(localName = "sendISDResponse", targetNamespace = "tns:ns", className = "com.ft.soap.SendISDResponse")
    @WebResult(name = "response", targetNamespace = "tns:ns")
    public com.ft.soap.Result sendISD(
        @WebParam(name = "tid", targetNamespace = "tns:ns")
        java.lang.String tid,
        @WebParam(name = "msisdn", targetNamespace = "tns:ns")
        java.lang.String msisdn
    );
}
