package com.ft.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-10-23T15:16:09.543+07:00
 * Generated source version: 3.2.6
 *
 */
@WebServiceClient(name = "SOAP_MCA",
                  targetNamespace = "tns:ns")
public class SOAPMCA_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("tns:ns", "SOAP_MCA");
    public final static QName SOAPMCA = new QName("tns:ns", "SOAP_MCA");
    static {
        URL url = null;
        try {
            url = SOAPMCA_Service.class.getClassLoader().getResource("soap/SOAP_MCA.wsdl");
        } catch (Exception e) {
            java.util.logging.Logger.getLogger(SOAPMCA_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SOAPMCA_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SOAPMCA_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SOAPMCA_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SOAPMCA_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SOAPMCA_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SOAPMCA_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns SOAPMCA
     */
    @WebEndpoint(name = "SOAP_MCA")
    public SOAPMCA getSOAPMCA() {
        return super.getPort(SOAPMCA, SOAPMCA.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SOAPMCA
     */
    @WebEndpoint(name = "SOAP_MCA")
    public SOAPMCA getSOAPMCA(WebServiceFeature... features) {
        return super.getPort(SOAPMCA, SOAPMCA.class, features);
    }

}
