version: '2'
services:
    zookeeper:
        image: wurstmeister/zookeeper:3.4.6
        ports:
          - 2181:2181
    kafka:
        image: wurstmeister/kafka:1.0.0
        environment:
            KAFKA_ADVERTISED_HOST_NAME: localhost
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CREATE_TOPICS: "sms:1:1"
        ports:
            - 9092:9092
    manager:
        image: sheepkiller/kafka-manager
        environment:
            ZK_HOSTS: zookeeper:2181
            APPLICATION_SECRET: "letmein"
        ports:
            - 9000:9000
